name: estadometrobus
description: La aplicación móvil "Estado del Metrobús CDMX" está diseñada para proporcionar a los usuarios información actualizada sobre el estado del servicio del Metrobús en la Ciudad de México. Esta herramienta útil permite a los viajeros verificar rápidamente el estado de las líneas y estaciones del Metrobús, asegurándose de que puedan planificar sus viajes de manera eficiente y evitar interrupciones inesperadas.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  beautiful_soup_dart: ^0.3.0
  http: ^0.13.6
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
